# Configuration options for Source2Book
sourcefolder: '/home/riccardo/CodeLite/Lippman/GCC_4_7_0'
title: 'C++ Primer Source Code'
subfolders: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15', '16', '17', '18', '19']
filter:
  - cc
  - h
headingrows: 29
